name: Deploy React App to AWS S3 and CloudFront

on:
  push:
    branches:
      - develop  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: secrets
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Verify build output
      run: ls -la ./dist

    - name: Export AWS Credentials
      run: |
        export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
        export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Debug environment variables
      run: env | grep AWS

    - name: S3/CloudFront Deploy
      uses: staevs/s3-deploy-action@1.2.4
      if: success()
      with:
        args: --follow-symlinks --delete --no-progress
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: "us-east-1"
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        

    - name: Invalidate CloudFront
      uses: chetan/invalidate-cloudfront-action@v2
      env:
        DISTRIBUTION: ${{ secrets.AWS_DISTRIBUTION_ID }}
        PATHS: "/index.html"
        AWS_REGION: "us-east-1"
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}